pipeline {
    agent {
        label 'AGENT-1' 
    }
    options{
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds() 
    }
    parameters{
        choice{name: 'ACTION', choices: ['apply', 'destroy'], description: 'select action'} 
    }
    stages {
        stage('Init') { 
            steps { 
                sh 'cd 00-VPC'  
                sh 'terraform init -reconfigure'  
            }
        }
        stage('Plan') { 
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-credentials') { 
                    sh 'cd 00-VPC'
                    sh 'terraform plan -out=tfplan' 
                } 
            }
        }
        stage('Deploy') { 
            steps { 
                sh 'echo this is deployment' 
            }
        }
    } 
    post{
        always{
            echo "this section runs always" 
            deleteDir() 
        }
        success{
            echo "this section runs when pipeline is success"
        }
        failure{
            echo "this section runs when pipeline is failure" 
        }
    }
} 