pipeline {
    agent {
        label 'AGENT-1' 
    }
    options{
        timeout(time: 30, unit: 'MINUTES') 
        disableConcurrentBuilds() 
        ansiColor('xterm') 
    }
    parameters{
        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'select action')
    }
    stages {
        stage('Init and Plan') { 
            steps { 
                withAWS(region: 'us-east-1', credentials: 'aws-credentials') {
                    sh """
                        cd 00-VPC  
                        terraform init -reconfigure
                        terraform plan -out=tfplan
                  
                    """
                } 
            }
        }
    } 
    post{
        always{
            echo "this section runs always" 
            deleteDir() 
        }
        success{
            echo "this section runs when pipeline is success"
        }
        failure{
            echo "this section runs when pipeline is failure" 
        }
    }
} 